spring.application.name=myapp

api.prefix=/api/v1

# Disable DataSource auto-configuration since we're using MongoDB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.config.import=optional:classpath:env.properties
# spring.config.import=vps-env.properties
# spring.config.import=publish-env.properties
# spring.config.import=docker-env.properties
# spring.config.import=publish-env.properties

spring.data.mongodb.uri=${MONGODB_URL:mongodb://localhost:27017/warcup}
spring.data.mongodb.database=${MONGODB_DB_NAME:warcup}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}




logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.example.myapp=DEBUG
logging.level.org.springframework.messaging=DEBUG


jwt.secret=${JWT_SECRET:dev-secret-change-me}
# in seconds
jwt.valid-duration:${JWT_VALID_DURATION:3600}
# in seconds
jwt.refresh-duration:${JWT_REFRESH_DURATION:86400}

server.address=${SPRING_SERVER_ADDRESS:0.0.0.0}
server.port=${SPRING_SERVER_PORT:8080}


netty.server.address=${NETTY_SERVER_ADDRESS:0.0.0.0}
netty.server.port=${NETTY_SERVER_PORT:8386}


game.tick-interval-ms=33